# Generated by Django 4.0.5 on 2022-10-05 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='listing_id',
        ),
    ]
