# Generated by Django 4.0.5 on 2022-10-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_contact_listing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique_for_date='published'),
        ),
    ]
