# Generated by Django 4.0.5 on 2022-10-08 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_listing_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='realtor',
        ),
        migrations.AddField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='property.realtor'),
        ),
    ]
