# Generated by Django 4.0.5 on 2022-10-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_remove_contact_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='cover_image',
            new_name='image',
        ),
    ]
