# Generated by Django 4.0.5 on 2022-10-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_rename_cover_image_listing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='realtor',
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
